"""Runtime constants shared by DJI Power manager components."""
from __future__ import annotations

NOTIFY_WATCHDOG_TIMEOUT = 30.0
GATT_WRITE_TIMEOUT = 10.0
START_NOTIFY_TIMEOUT = 10.0
HMS_PATTERN_HISTORY_LIMIT = 20
STALE_CONNECTION_CLEANUP_FIRST_FAILURE_COUNT = 2
STALE_CONNECTION_CLEANUP_INTERVAL = 3
ESTABLISH_CONNECTION_MAX_ATTEMPTS = 2
UNEXPECTED_DISCONNECT_SETTLE_SECONDS = 5.0
FRESH_ADVERTISEMENT_TIMEOUT_SECONDS = 60.0
CONNECTION_EVENT_HISTORY_LIMIT = 50
EXPECTED_DISCONNECT_RECORD_TTL_SECONDS = 300.0
RECONNECT_BACKOFF_SECONDS = (10.0, 30.0, 60.0, 120.0, 300.0)
CONFIG_CACHE_MAX_AGE_SECONDS = 30.0
OUTPUT_TABLE_CACHE_MAX_AGE_SECONDS = 15.0
